name: CI_pytest_appendfilename

# name    : pytest.yml
# purpose : regularly run pytest on appendfilename
# date    : [2024-10-31 Thu]
# edit    : [2026-05-11 Mon]

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - master
  workflow_dispatch:     # provide a manual trigger
  # schedule:
    # - cron: "0 0 1 * *"  # once each 1st of a month, at 00:00 UTC (cf. https://crontab.guru/)

jobs:
  test:
    strategy:
      matrix:
        # a factorial test which permutates the latest os runners with the most
        # recent Python interpreter available, see
        # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
        # state of commit 23478d3 as visited on 2025-05-07 Wed
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.x"]
    runs-on: ${{ matrix.os }}

    timeout-minutes: 5  # Timeout for each job individually

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies with PyPI
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest
          pip list

      - name: run the check by pytest
        run: |
          echo "default"
          python -m pytest -m "default"
          echo "prepend"
          python -m pytest -m "prepend"
          echo "smart_prepend"
          python -m pytest -m "smart_prepend"

